### ISSUE TITLE
menu obscures map on mobile

### ISSUE THREAD

**Issue by alicewriteswrongs** [AntiEvictionBoston/antievictionboston.github.io#34]
the nav menu up to is obscuring most of the map on mobile:

![menu](https://cloud.githubusercontent.com/assets/6207644/13751596/45fdc88c-e9e1-11e5-8a83-ef8177695492.png)

**Comment by alicewriteswrongs** [comment]
I see this on my phone (android + chrome for android) and on the desktop with chrome's mobile simulator.

**Comment by heybenji** [comment]
Yes it is very sad. Known issue @aliceriot. I'm going to refactor the navbar now-ish.
