### ISSUE TITLE
maps.js should really reference the production CDN version with a SHA

### ISSUE THREAD

**Issue by heybenji** [AntiEvictionBoston/antievictionboston.github.io#36]
Hey @aliceriot I need to take a break for an hour or so if you have a minute can you switch _layouts/map.html to use the latest SHA of the utility repo on cdn.rawgit? @pizzavangelist seems to think the map is slow and I have a feeling we'll get throttled pretty soon as press heats up.

**Comment by alicewriteswrongs** [comment]
yah I can do that

I think I have a small CSS change for the header I'd like to run by you too, in a sec

**Comment by alicewriteswrongs** [comment]
its #38 if you wanna take a look!

**Comment by alicewriteswrongs** [comment]
also I already merged the script sourcing change in #37

**Comment by heybenji** [comment]
Fixed by #37 calling it closed. Issue freeeeeeee!
