### ISSUE TITLE
Add rent burdened map

### ISSUE THREAD

**Issue by heybenji** [AntiEvictionBoston/antievictionboston.github.io#49]
Thing’s we’ll need:
1. 16:9 screenshot of map (probably without any text in the screenshot—no definition, etc) for thumbnail.
2. Title of map for website homepage (and menu).
3. Short description of map (similar to what’s there for the tenant stories map).
4. Embed code for the map.

Creating an issue for this. It will probably involve a little bit of a refactor of the _layouts/map.html file. I have something in mind already.

Psst... @pizzavangelist @beccalou @aliceriot

**Comment by alicewriteswrongs** [comment]
sounds good! I think that should be all we need.

**Comment by heybenji** [comment]
Collecting stuff from @pizzavangelist:

TITLE: Concentrations of "rent-burdened" tenants in Boston

DESCRIPTION: Where are Boston renters paying 30% or more of their income in rent? It's a longstanding financial rule-of-thumb that if a tenant is paying 30% or more of their income in rent, it's no longer an affordable or stable tenancy. This map shows where people are paying rent beyond their means - and where people are most at risk of displacement by rent increase.

**Comment by heybenji** [comment]
Starting to work on this.
