### ISSUE TITLE
Rent-burdened map does not scroll in Chrome Responsive Device Mode

### ISSUE THREAD

**Issue by heybenji** [AntiEvictionBoston/antievictionboston.github.io#54]
See #50 for more context. We need to test the map on an actual Android device.

Regardless, fixing it will involve bothering CartoDB, as raw map also does scroll on Chrome Responsive Device Mode.

**Comment by heybenji** [comment]
@aliceriot can you check out the rent burdened map on your phone now that it's live and confirm/disconfirm panning is broken?

**Comment by alicewriteswrongs** [comment]
Just checked on my phone and it pans around just fine! I also have
pinch-to-zoom and stuff.

**Comment by heybenji** [comment]
Whew! Closing!
