### ISSUE TITLE
Footer bumps up against viewport on mobile

### ISSUE THREAD

**Issue by heybenji** [AntiEvictionBoston/antievictionboston.github.io#58]
Looks kind of sad. :-(

![simulator screen shot mar 24 2016 8 37 49 pm](https://cloud.githubusercontent.com/assets/42669/14035076/4e84b66a-f200-11e5-8191-2708a8d7ec92.png)

**Comment by heybenji** [comment]
@beccalou any chance you want to take a stab at this? I'm betting it's as simple as putting a `.row` or `.container` class somewhere in the footer.

**Comment by beccalou** [comment]
Yes!  I'm all over it-- is this weekend soon enough?

**Comment by heybenji** [comment]
Totally. It's not urgent, but does break the magic circle when you're on a phone. Just be sure to pull master before branching and making the change. Made quite a few CSS changes when pushing the Take Action page.

**Comment by beccalou** [comment]
Alrighty-- pull request is pending...
