### ISSUE TITLE
something is wacky w/ jekyll

### ISSUE THREAD

**Issue by alicewriteswrongs** [AntiEvictionBoston/antievictionboston.github.io#6]
here's a screenshot of what the current version of the map looks like in jekyll on mobile: 

![map_on_jekyll](https://cloud.githubusercontent.com/assets/6207644/13379895/185e86a0-de01-11e5-91b5-99ab70f9322b.png)

I'm not sure exactly what's going on, this is what the map looks like on mobile on it's own right now:

![current_map](https://cloud.githubusercontent.com/assets/6207644/13379896/249f638a-de01-11e5-94d6-449f046261ff.png)

**Comment by heybenji** [comment]
Caching issue? Or, there was some baked in stuff in the template from V1 that I can probably pull out with the new styles.

**Comment by heybenji** [comment]
This is fixed by #8 so I'm closing
